name: Build
on: [push]

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Install
        run: npm ci
        
      - name: Lint
        run: npm run lint
        

  test: 
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Install
        run: npm ci
        
      - name: Run Tests
        run: npm run test
        

  build: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Install
        run: npm ci
        
      - name: Create Build
        run: npm run build
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: artifact
          path: ./dist
          
